// <auto-generated />
using System;
using CDRAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CDRAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230524173906_CreateCallRecord")]
    partial class CreateCallRecord
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.LookupModels.Currency", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Domain.Models.CallRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CallDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CallerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int?>("Currency")
                        .HasColumnType("int");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Recipient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CallDate");

                    b.HasIndex("CallerId");

                    b.HasIndex("Currency");

                    b.ToTable("CallRecords");
                });

            modelBuilder.Entity("Domain.Models.CallRecord", b =>
                {
                    b.HasOne("Domain.LookupModels.Currency", "Currencys")
                        .WithMany()
                        .HasForeignKey("Currency");

                    b.Navigation("Currencys");
                });
#pragma warning restore 612, 618
        }
    }
}
